#!/bin/bash

# Automounter for removable media
udiskie &

# Wallpaper Backend
swww-daemon --format xrgb &

# Bar
waybar &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Notify about devices connecting and disconnecting
devify &

# Idle daemon to screen lock
hypridle &

# Clipboard
wl-paste --watch cliphist store &

# Audio
easyeffects --gapplication-service &
