gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#313244"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#45475a"
    cherryPickedCommitBgColor:
      - "#a6e3a1"
    cherryPickedCommitFgColor:
      - "#1e1e2e"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
